server:
  port: 8002

spring:
  application:
    name: Address-Service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8123
#
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#spring:
#