server:
  port: 8123

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YashKakrechaInexture/cloud-config-demo
          clone-on-start: true